### ISSUE TITLE
link error: undefined reference to `pow'

### ISSUE THREAD

**Issue by john-wilkes** [hpcgarage/spatter#33] opened 2019-07-30 18:19 UTC
Ubuntu 16.04.4 LTS
gcc version 5.4.0

In build_omp_gnu:

[100%] Linking C executable spatter
/spatter.dir/src/json.c.o: In function `json_parse_ex':
json.c:(.text+0xe2a): undefined reference to `pow'
json.c:(.text+0x1466): undefined reference to `pow'
collect2: error: ld returned 1 exit status
CMakeFiles/spatter.dir/build.make:233: recipe for target 'spatter' failed

**Comment by plavin** [comment] 2019-08-01 19:47
Sorry to take so long to get back to you. I don't have access to gcc 5.4 right this second, and I'm unable to reproduce this on my current machine. However, I changed the CMakeLists.txt to link the math library in the proper way (using target_link_libraries). Could pull the changes from the recent merge and you see if this fixes it for you? 

If not, I'll grab 5.4 and try again to reproduce it.

**Comment by john-wilkes** [comment] 2019-08-01 19:59
I was able to get it to link by modifying build_omp_gnu/CMakeFiles/spatter.dir/link.txt.

The “-lm” option needs to be after the .o files.

Original link.txt:

/usr/bin/gcc -O3 -DSPAT_C_NAME=GNU -lm -I/home/jwilkes/spatter-master/include -fopenmp -fopenmp -DSPAT_C="/usr/bin/gcc" -DSPAT_C_VER="5.4.0" -O3 -DNDEBUG    CMakeFiles/spatter.dir/src/backend-support-tests.c.o … -o spatter

Changed to:

/usr/bin/gcc -O3 -DSPAT_C_NAME=GNU -I/home/jwilkes/spatter-master/include -fopenmp -fopenmp -DSPAT_C="/usr/bin/gcc" -DSPAT_C_VER="5.4.0" -O3 -DNDEBUG    CMakeFiles/spatter.dir/src/backend-support-tests.c.o …  -lm  -o spatter

Then I sourced link.txt.

I’ll pull the changes and see if you fixed it “the right way”.   :-)

John

**Comment by jyoung3131** [comment] 2019-08-02 13:58
I also just checked the latest commit 9f2444 and it seems to work on an Ubuntu 16 box we have with gcc 5.4.0 and it seems to link -lm at the end (so properly). Will wait a little bit to hear back, but I think the latest commit should fix this bug.

```
/home/jeff/local/cmake/bin/cmake -E cmake_link_script CMakeFiles/spatter.dir/link.txt --verbose=1
/usr/bin/gcc -O3 -DSPAT_C_NAME=GNU -O3 -I/home/jeff/git_repos/spatter/spatter/include -fopenmp -fopenmp -DSPAT_C="/usr/bin/gcc" -DSPAT_C_VER="5.4.0" -O3 -DNDEBUG    CMakeFiles/spatter.dir/src/backend-support-tests.c.o CMakeFiles/spatter.dir/src/json.c.o CMakeFiles/spatter.dir/src/main.c.o CMakeFiles/spatter.dir/src/mt19937-64.c.o CMakeFiles/spatter.dir/src/parse-args.c.o CMakeFiles/spatter.dir/src/sgbuf.c.o CMakeFiles/spatter.dir/src/sgtime.c.o CMakeFiles/spatter.dir/src/sp_alloc.c.o CMakeFiles/spatter.dir/src/trace-util.c.o CMakeFiles/spatter.dir/src/vrand.c.o CMakeFiles/spatter.dir/src/openmp/openmp_kernels.c.o  -o spatter -lm 
```

**Comment by jyoung3131** [comment] 2019-08-06 19:45
Closing as fix has been merged - please reach out if this pops up again, John!

**Closed by jyoung3131** 2019-08-06 19:45 UTC
Labels: bug
